services:
  backend:
    build:
      context: ./backend
    image: sbenaissa/fiona-chatbot-backend:latest
  frontend:
    build:
      context: ./frontend
    image: sbenaissa/fiona-chatbot-frontend:latest