name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Check for requirements.txt
      run: |
        if [ ! -f backend/requirements.txt ]; then
          echo "Error: requirements.txt not found in backend directory."
          exit 1
        fi

    - name: Install backend dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Run backend tests
      run: |
        cd backend
        python -m pytest

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Check for docker-compose.yml
      run: |
        if [ ! -f docker-compose.yml ]; then
          echo "Error: docker-compose.yml not found in the root directory."
          exit 1
        fi

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Deploy with Docker Compose
      run: |
        docker-compose up --build -d

    - name: Cleanup unused Docker resources
      run: |
        docker system prune -f